main: me.schlaubi.kaesk.GameModePlugin
name: GameModePlugin
version: '1.0'
author: mik
api-version: '1.13'
commands:
  gamemode:
    usage: "Usage: /gamemode <mode> <player>"
  say:
  sum:
  test:
  vanish:
